services:
  runtime_builder:
    image: arm64v8/debian:bullseye
    platform: linux/arm64
    command:
      - "/bin/bash"
      - "-lc"
      - "/local/build-runtime-minui.sh 2>&1"
    env_file:
      - build-config
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /local
